default_context:
  project_name: 'kurirku'
  project_slug: 'kurirku'
  domain_main: 'kurirku.com'
  domain_staging: 'stag.kurirku.com'
  docker_swarm_stack_name_main: 'kurirku-com'
  docker_swarm_stack_name_staging: 'stag-kurirku-com'
  secret_key: 'secret'
  first_superuser: 'admin@kurirku.com'
  first_superuser_password: 'secret'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.kurirku.com", "https://stag.kurirku.com", "https://kurirku.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@kurirku.com'
  postgres_password: 'secret'
  pgadmin_default_user: 'admin@kurirku.com'
  pgadmin_default_user_password: 'secret'
  traefik_constraint_tag: 'kurirku.com'
  traefik_constraint_tag_staging: 'stag.kurirku.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:secret'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
